# Generated by Django 4.0.1 on 2022-01-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sdate', models.DateField(default='2022-01-01')),
                ('edate', models.DateField(default='2022-01-01')),
                ('photo', models.ImageField(default='default.png', upload_to='')),
                ('expires_in', models.CharField(default='', max_length=20)),
                ('vendor_email', models.EmailField(default='', max_length=50)),
                ('vendor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
