# Generated by Django 3.2 on 2022-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_notify', '0002_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
