# Generated by Django 3.2 on 2022-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_notify', '0004_products_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='expires_in',
            field=models.IntegerField(default=0),
        ),
    ]
