# Generated by Django 3.2 on 2023-02-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_notify', '0005_alter_products_expires_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('expires_in', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('auto_renew', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='payment_mode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
