# Generated by Django 3.2 on 2023-07-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products_notify', '0006_auto_20230205_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('expires_in', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('auto_renew', models.IntegerField(default=0)),
            ],
        ),
    ]
